-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS "Ekenox".arranjo
(
    sku text COLLATE pg_catalog."default" NOT NULL,
    nomeproduto text COLLATE pg_catalog."default" NOT NULL,
    quantidade double precision NOT NULL,
    chapa text COLLATE pg_catalog."default" NOT NULL,
    material text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_arrando_sku PRIMARY KEY (sku)
);

CREATE TABLE IF NOT EXISTS "Ekenox".categoria
(
    "categoriaId" bigint NOT NULL,
    "nomeCategoria" text COLLATE pg_catalog."default",
    "categoriaPai" bigint,
    CONSTRAINT categoria_pkey PRIMARY KEY ("categoriaId")
);

CREATE TABLE IF NOT EXISTS "Ekenox".contatos
(
    "idContato" bigint NOT NULL,
    nome text COLLATE pg_catalog."default",
    "tipoPessoa" "char",
    "numeroDOcumento" text COLLATE pg_catalog."default",
    CONSTRAINT "Contatos_pkey" PRIMARY KEY ("idContato")
);

CREATE TABLE IF NOT EXISTS "Ekenox".deposito
(
    id bigint NOT NULL,
    descricao text COLLATE pg_catalog."default",
    situacao text COLLATE pg_catalog."default",
    padrao boolean DEFAULT false,
    desconsiderarsaldo boolean DEFAULT false,
    CONSTRAINT deposito_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "Ekenox".estoque
(
    "fkProduto" text COLLATE pg_catalog."default" NOT NULL,
    "saldoFisico" double precision,
    "saldoVirtual" double precision,
    CONSTRAINT estoque_pkey PRIMARY KEY ("fkProduto")
);

CREATE TABLE IF NOT EXISTS "Ekenox".estrutura
(
    fkproduto text COLLATE pg_catalog."default",
    componente text COLLATE pg_catalog."default",
    quantidade double precision,
    dados text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT estruruta_pkey PRIMARY KEY (dados)
);

CREATE TABLE IF NOT EXISTS "Ekenox".etiqueta
(
    "fkPedido" bigint NOT NULL,
    nome text COLLATE pg_catalog."default",
    endereco text COLLATE pg_catalog."default",
    numero text COLLATE pg_catalog."default",
    complemento text COLLATE pg_catalog."default",
    municipio text COLLATE pg_catalog."default",
    uf text COLLATE pg_catalog."default",
    cep text COLLATE pg_catalog."default",
    bairro text COLLATE pg_catalog."default",
    CONSTRAINT "Etiqueta_pkey" PRIMARY KEY ("fkPedido")
);

CREATE TABLE IF NOT EXISTS "Ekenox".fornecedor
(
    nome text COLLATE pg_catalog."default",
    codigo text COLLATE pg_catalog."default",
    situacao character varying COLLATE pg_catalog."default",
    "numeroDocumentacao" double precision,
    telefone text COLLATE pg_catalog."default",
    celular text COLLATE pg_catalog."default",
    "idFornecedor" bigint NOT NULL,
    CONSTRAINT fornecedor_pkey PRIMARY KEY ("idFornecedor")
);

CREATE TABLE IF NOT EXISTS "Ekenox"."infoProduto"
(
    "estoqueMinimo" double precision,
    "estoqueMaximo" double precision,
    "estoqueLocalizacao" text COLLATE pg_catalog."default",
    unidade text COLLATE pg_catalog."default",
    "pesoLiquido" double precision,
    "pesoBruto" double precision,
    volumes double precision,
    "itensPorCaixa" double precision,
    gtin text COLLATE pg_catalog."default",
    "tipoProducao" text COLLATE pg_catalog."default",
    marca text COLLATE pg_catalog."default",
    "precoCompra" double precision,
    largura double precision,
    altura double precision,
    profundidade double precision,
    "unidadeMedida" text COLLATE pg_catalog."default",
    "fkFornecedor" bigint,
    "fkCategoria" bigint,
    "fkProduto" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "fkProduto" PRIMARY KEY ("fkProduto")
);

CREATE TABLE IF NOT EXISTS "Ekenox".itens
(
    id bigint NOT NULL,
    codigo text COLLATE pg_catalog."default",
    unidade text COLLATE pg_catalog."default",
    quantidade double precision,
    desconto double precision,
    valor double precision,
    "nomeProduto" text COLLATE pg_catalog."default",
    "fkProduto" text COLLATE pg_catalog."default",
    "fkPedido" bigint,
    "dataPedido" timestamp without time zone,
    CONSTRAINT itens_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "Ekenox".num_op
(
    num_op bigint NOT NULL,
    CONSTRAINT num_op_pkey PRIMARY KEY (num_op)
);

CREATE TABLE IF NOT EXISTS "Ekenox".ordem_producao
(
    id bigint NOT NULL,
    numero bigint NOT NULL,
    deposito_id_destino bigint,
    deposito_id_origem bigint,
    situacao_id bigint,
    responsavel text COLLATE pg_catalog."default",
    fkprodutoid text COLLATE pg_catalog."default" NOT NULL,
    data_previsao_inicio date,
    data_previsao_final date,
    data_inicio date,
    data_fim date,
    valor numeric(10, 2),
    observacao text COLLATE pg_catalog."default",
    quantidade numeric(10, 2),
    CONSTRAINT ordem_producao_pkey PRIMARY KEY (id),
    CONSTRAINT ordem_producao_numero_unique UNIQUE (numero)
);

CREATE TABLE IF NOT EXISTS "Ekenox".ordem_producao_situacao_audit
(
    audit_id bigserial NOT NULL,
    ordem_producao_id bigint NOT NULL,
    fkprodutoid text COLLATE pg_catalog."default" NOT NULL,
    situacao_id_old bigint,
    situacao_id_new bigint,
    changed_at timestamp with time zone NOT NULL DEFAULT now(),
    changed_by text COLLATE pg_catalog."default" NOT NULL DEFAULT CURRENT_USER,
    CONSTRAINT ordem_producao_situacao_audit_pkey PRIMARY KEY (audit_id)
);

CREATE TABLE IF NOT EXISTS "Ekenox".pedidos
(
    "idPedido" bigint NOT NULL,
    numero bigint,
    "numeroLoja" text COLLATE pg_catalog."default",
    data date,
    "dataSaida" date,
    "totalProdutos" double precision,
    total double precision,
    "fkContato" bigint,
    "fkSituacao" bigint,
    "fkLoja" bigint,
    conta text COLLATE pg_catalog."default",
    "numeroPedidoCompra" text COLLATE pg_catalog."default",
    "outrasDespesas" double precision,
    observacoes text COLLATE pg_catalog."default",
    "observacoesInternas" text COLLATE pg_catalog."default",
    desconto double precision,
    moeda text COLLATE pg_catalog."default",
    "taxaComissao" double precision,
    "custoFrete" double precision,
    "valorBase" double precision,
    CONSTRAINT "Pedido_pkey" PRIMARY KEY ("idPedido")
);

CREATE TABLE IF NOT EXISTS "Ekenox".produtos
(
    "produtoId" text COLLATE pg_catalog."default" NOT NULL,
    "nomeProduto" text COLLATE pg_catalog."default",
    sku text COLLATE pg_catalog."default",
    preco double precision,
    custo double precision,
    tipo text COLLATE pg_catalog."default",
    formato text COLLATE pg_catalog."default",
    "descricaoCurta" text COLLATE pg_catalog."default",
    "idProdutoPai" text COLLATE pg_catalog."default",
    "fkCategoriaId" integer,
    "Categoria" text COLLATE pg_catalog."default",
    "descImetro" text COLLATE pg_catalog."default",
    CONSTRAINT produtos_pkey PRIMARY KEY ("produtoId")
);

CREATE TABLE IF NOT EXISTS "Ekenox".sequenciadores
(
    tabela character varying(30) COLLATE pg_catalog."default" NOT NULL,
    sequenciador bigint NOT NULL,
    CONSTRAINT sequenciadores_pkey PRIMARY KEY (tabela)
);

CREATE TABLE IF NOT EXISTS "Ekenox".situacao
(
    id bigint NOT NULL,
    nome text COLLATE pg_catalog."default",
    "idHerdado" bigint,
    CONSTRAINT situacao_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "Ekenox".token
(
    id bigint NOT NULL,
    created_at timestamp with time zone,
    integracao text COLLATE pg_catalog."default",
    client_id text COLLATE pg_catalog."default",
    client_secret text COLLATE pg_catalog."default",
    access_token text COLLATE pg_catalog."default",
    refresh_token text COLLATE pg_catalog."default",
    expires_at timestamp with time zone,
    CONSTRAINT token_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS "Ekenox".estoque
    ADD CONSTRAINT "Produto" FOREIGN KEY ("fkProduto")
    REFERENCES "Ekenox".produtos ("produtoId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS estoque_pkey
    ON "Ekenox".estoque("fkProduto");


ALTER TABLE IF EXISTS "Ekenox".estrutura
    ADD CONSTRAINT componente FOREIGN KEY (componente)
    REFERENCES "Ekenox".produtos ("produtoId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Ekenox".estrutura
    ADD CONSTRAINT produto FOREIGN KEY (fkproduto)
    REFERENCES "Ekenox".produtos ("produtoId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Ekenox".etiqueta
    ADD CONSTRAINT "Pedido" FOREIGN KEY ("fkPedido")
    REFERENCES "Ekenox".pedidos ("idPedido") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "Etiqueta_pkey"
    ON "Ekenox".etiqueta("fkPedido");


ALTER TABLE IF EXISTS "Ekenox"."infoProduto"
    ADD CONSTRAINT "Categoria" FOREIGN KEY ("fkCategoria")
    REFERENCES "Ekenox".categoria ("categoriaId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Categoria"
    ON "Ekenox"."infoProduto"("fkCategoria");


ALTER TABLE IF EXISTS "Ekenox"."infoProduto"
    ADD CONSTRAINT "Fornecedor" FOREIGN KEY ("fkFornecedor")
    REFERENCES "Ekenox".fornecedor ("idFornecedor") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Fornecedor"
    ON "Ekenox"."infoProduto"("fkFornecedor");


ALTER TABLE IF EXISTS "Ekenox"."infoProduto"
    ADD CONSTRAINT "Produto" FOREIGN KEY ("fkProduto")
    REFERENCES "Ekenox".produtos ("produtoId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Produto"
    ON "Ekenox"."infoProduto"("fkProduto");


ALTER TABLE IF EXISTS "Ekenox".itens
    ADD CONSTRAINT "Pedido" FOREIGN KEY ("fkPedido")
    REFERENCES "Ekenox".pedidos ("idPedido") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Ekenox".itens
    ADD CONSTRAINT "Produto" FOREIGN KEY ("fkProduto")
    REFERENCES "Ekenox".produtos ("produtoId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Ekenox".ordem_producao
    ADD CONSTRAINT fk_op_produto FOREIGN KEY (fkprodutoid)
    REFERENCES "Ekenox".produtos ("produtoId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS "Ekenox".ordem_producao
    ADD CONSTRAINT ordem_producao_deposito_id_fkey FOREIGN KEY (deposito_id_origem)
    REFERENCES "Ekenox".deposito (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS "Ekenox".ordem_producao
    ADD CONSTRAINT ordem_producao_situacao_id_fkey FOREIGN KEY (situacao_id)
    REFERENCES "Ekenox".situacao (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS "Ekenox".ordem_producao_situacao_audit
    ADD CONSTRAINT fk_audit_new FOREIGN KEY (situacao_id_new)
    REFERENCES "Ekenox".situacao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Ekenox".ordem_producao_situacao_audit
    ADD CONSTRAINT fk_audit_old FOREIGN KEY (situacao_id_old)
    REFERENCES "Ekenox".situacao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Ekenox".ordem_producao_situacao_audit
    ADD CONSTRAINT fk_audit_op FOREIGN KEY (ordem_producao_id)
    REFERENCES "Ekenox".ordem_producao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Ekenox".ordem_producao_situacao_audit
    ADD CONSTRAINT fk_op_produto FOREIGN KEY (fkprodutoid)
    REFERENCES "Ekenox".produtos ("produtoId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS "Ekenox".pedidos
    ADD CONSTRAINT "Contato" FOREIGN KEY ("fkContato")
    REFERENCES "Ekenox".contatos ("idContato") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Ekenox".pedidos
    ADD CONSTRAINT "Situação" FOREIGN KEY ("fkSituacao")
    REFERENCES "Ekenox".situacao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;